Completed dom-querying exercise  -  Omid Asadi
omidzed/c-0823-code-solutions pull request #30
Opened 2023-09-11 18:31 UTC by omidzed

![image](https://github.com/omidzed/c-0823-code-solutions/assets/136918229/cb825779-e5f5-4f82-a202-4b3baa0a2b3f)

2023-09-11 20:43 UTC, shawnkost requested changes
One change here Omid!

2023-09-11 20:43 UTC, shawnkost commented on dom-querying/main.js
> +const $paragraphs = document.querySelectorAll('.p');
This should just be `p` without the `.`. `.p` means you're querying for a class p rather than the `p` element

2023-09-11 20:54 UTC, omidzed commented on dom-querying/main.js
> +const $paragraphs = document.querySelectorAll('.p');
Made the  change,  and here is the updated screenshot showing the NodeList

![image](https://github.com/omidzed/c-0823-code-solutions/assets/136918229/c1f2f2d7-bb2d-4f76-9986-790f99a4a314)

2023-09-12 17:45 UTC, shawnkost approved these changes
👍🏻

2023-09-12 17:57 UTC, merged